package hattmakeri;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class ExempelHattar extends javax.swing.JPanel {

    private ArrayList<ImageIcon> bildListaHattar;
    private ArrayList<String> hattTextLista;

    /**
     * Creates new form ExempelHattar
     */
    public ExempelHattar() {
        initComponents();
        this.bildListaHattar = new ArrayList();
        skapaHattTextLista();
        btnFörfrågan.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        comboBoxHattar = new javax.swing.JComboBox<>();
        labHattExempel = new javax.swing.JLabel();
        labHattText = new javax.swing.JLabel();
        btnFörfrågan = new javax.swing.JButton();
        labUnderRubrik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel2.setText("Exempelhattar");

        comboBoxHattar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj hatt", "Modell 1", "Modell 2", "Modell 3", "Modell 4" }));
        comboBoxHattar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHattarActionPerformed(evt);
            }
        });

        labHattExempel.setText("Bild kommer inom kort!");

        labHattText.setText("Här visas hatt-info när hatt valts");

        btnFörfrågan.setText("Skicka förfrågan");
        btnFörfrågan.setToolTipText("<html>Faller en exempelhatt dig i smaken?<br>Klicka här för att skapa en beställningsförfrågan!</html>\n");

        labUnderRubrik.setText("Ta en titt på våra lagerförda hattar för inspiration!");

        jButton1.setText("Specialbeställning");
        jButton1.setToolTipText("<html>Inte hittat precis rätt?<br>Klicka här för att skicka en förfrågan om specialbeställning!</html>\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labHattExempel)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxHattar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labHattText))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labUnderRubrik)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(btnFörfrågan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labUnderRubrik)
                .addGap(48, 48, 48)
                .addComponent(comboBoxHattar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(btnFörfrågan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labHattExempel)
                            .addComponent(labHattText))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxHattarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHattarActionPerformed
        int index = comboBoxHattar.getSelectedIndex();
        if(!bildListaHattar.isEmpty()){
       
        if(index!=0){
        int index2 = index - 1;
        ImageIcon bild = bildListaHattar.get(index2);
        String hattText= hattTextLista.get(index2);
        labHattExempel.setIcon(bild);
        labHattText.setText(hattText);
        btnFörfrågan.setEnabled(true);}
        
        else
        {
         labHattExempel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\com.mycompany_Grupp13Scrumm_jar_1.0-SNAPSHOT\\src\\main\\java\\bilderHattar\\bakgrund.png"));
         labHattText.setText("");
         btnFörfrågan.setEnabled(false);
        
        }}
        else{
            
        
        
        
        }
    }//GEN-LAST:event_comboBoxHattarActionPerformed

    private void skapaBildListaHattar() {
        bildListaHattar = new ArrayList<>();
        bildListaHattar.add(new ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\com.mycompany_Grupp13Scrumm_jar_1.0-SNAPSHOT\\src\\main\\java\\bilderHattar\\modell1.png"));
        bildListaHattar.add(new ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\com.mycompany_Grupp13Scrumm_jar_1.0-SNAPSHOT\\src\\main\\java\\bilderHattar\\modell2.png"));
        bildListaHattar.add(new ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\com.mycompany_Grupp13Scrumm_jar_1.0-SNAPSHOT\\src\\main\\java\\bilderHattar\\modell3.png"));
        bildListaHattar.add(new ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\com.mycompany_Grupp13Scrumm_jar_1.0-SNAPSHOT\\src\\main\\java\\bilderHattar\\modell4.png"));

       
        for (ImageIcon imageIcon : bildListaHattar) {
            System.out.println("Sökväg: " + imageIcon.getDescription());
        }

        System.out.println("Antal bilder i listan: " + bildListaHattar.size());
    }

    private void skapaHattTextLista() {
        hattTextLista = new ArrayList();
        hattTextLista.add("<html>'Tjusig hög svart hatt<br>i lyxigt utförande, i glansigt tyg.'</html>");
        hattTextLista.add("<html>'Fräsig trollkarlshatt i brunt.<br>Pråligt smycke i guld och rubin.'</html>");
        hattTextLista.add("<html>'Klotformad grå hatt för den som inte är rädd för att se fånig ut.'</html>");
        hattTextLista.add("<html>'Grön keps med röd bolltofs.<br>Perfekt för en mer ungdomlig look.'</html>");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFörfrågan;
    private javax.swing.JComboBox<String> comboBoxHattar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labHattExempel;
    private javax.swing.JLabel labHattText;
    private javax.swing.JLabel labUnderRubrik;
    // End of variables declaration//GEN-END:variables
}
